hyprwm/aquamarine

src/utils/FormatUtils.cpp

store format name in a std::string and free the char ptr to ensure we dont leak on each call to drmGetFormatName.

formatutils: ensure we dont leak name ptr

---

include/aquamarine/backend/DRM.hpp
include/aquamarine/backend/Headless.hpp
include/aquamarine/backend/Wayland.hpp
include/aquamarine/output/Output.hpp
src/backend/Headless.cpp
src/backend/Wayland.cpp
src/backend/drm/DRM.cpp
src/backend/drm/impl/Atomic.cpp
src/backend/drm/impl/Legacy.cpp
src/output/Output.cpp

Adds an optional `scheduleFrameReason` argument to `scheduleFrame`. Now it is used for tracing only. Later it can be used for stuff like `cursor:no_break_fs_vrr`

Add  scheduleFrame reasons

---

CMakeLists.txt

This would fix a cross-compile issue where hyprwayland-scanner is pulled in for target but needs to run on host.

CMakeLists.txt: require native hyprwayland-scanner

---

src/allocator/GBM.cpp

Use `attrs` instead of `params` since `guessFormatFrom` makes changes to `attrs` and other code also uses this var.
Fixes cursor buffer creation on nvidia.
Fixes `[ERR] [EGL] Command eglQueryDmaBufModifiersEXT errored out with EGL_BAD_PARAMETER (0x12300): EGL_BAD_PARAMETER error: In eglQueryDmaBufModifiersEXT: Invalid format` on hl side but rendering to this buffer still fails.

Fix cursor swapchain buffer creation

---

include/aquamarine/output/Output.hpp
src/backend/drm/impl/Atomic.cpp
src/output/Output.cpp

Handle `explicit*Fence` as wlroots does. `setExplicitOutFence` doesn't need an argument but I kept it for a while. It should be called when there is some active `wait_timeline`... whatever this might be.

pass explicitOutFence pointer and do not touch the value

---

include/aquamarine/buffer/Buffer.hpp

ensure we dont cast out of range in caps(),
return (Aquamarine::eBufferCapability)0; in GBM.cpp
one less out of range cast from #4

buffer: add a NONE flag to eBufferCapability

---

include/aquamarine/allocator/GBM.hpp
src/allocator/GBM.cpp

Expose gbm buffer mapping through `beginDataPtr`. The mapping is created only once so only flags passed for the first time are used. Can be used to copy data to the gbm buffer if rendering fails (`flags = GBM_BO_TRANSFER_WRITE`). Assumes 4 bytes per pixel as the most common case for cursor buffers.

Expose bo buffer mapping

---

include/aquamarine/backend/DRM.hpp
src/backend/Session.cpp
src/backend/drm/DRM.cpp

realized this while working on hyprwm/Hyprland#6875

handle monitor hotplugs and fix a few bugs that it revealed

---

src/backend/drm/DRM.cpp

Fixes crash with my VR headset plugged in

drm: fix crash for connectors without a fallback mode

---

include/aquamarine/backend/DRM.hpp
include/aquamarine/backend/Wayland.hpp
include/aquamarine/backend/drm/Atomic.hpp
include/aquamarine/backend/drm/Legacy.hpp
include/aquamarine/output/Output.hpp
src/backend/Wayland.cpp
src/backend/drm/DRM.cpp
src/backend/drm/impl/Atomic.cpp
src/backend/drm/impl/Legacy.cpp
src/output/Output.cpp

- Removes `needsFrame = true` before `scheduleFrame` since it is set inside. Useful for logging `needsFrame` changes.
- Adds optional `skipShedule` argument to `moveCursor` to allow `cursor:no_break_fs_vrr` with hw cursors
`skipShedule` requires HL updates to be useful. Just passing `true` to `moveCursor` is not enough to fix VRR. Probably needs something like https://github.com/hyprwm/Hyprland/pull/6877 for hw cursors.

Remove redundant needsFrame & allow frame schedule skipping on mouse move

---

include/aquamarine/backend/Backend.hpp
include/aquamarine/backend/DRM.hpp
include/aquamarine/backend/Misc.hpp
src/allocator/GBM.cpp
src/backend/Backend.cpp
src/backend/drm/DRM.cpp
src/backend/drm/Renderer.cpp
src/backend/drm/Renderer.hpp
src/include/FormatUtils.hpp

Nvidia cannot render to linear buffers part 2 the sequel
ref #26
ref https://github.com/hyprwm/Hyprland/issues/7005
needs testing

Nvidia fixes for scanout gbm allocation

---

src/backend/drm/DRM.cpp

Fixes #22.
A slightly more robust way to address the issue than the hack provided in #22 - done by checking if the driver being used for the given GPU is `evdi`. If so, set `primary` to `{}`.
Unsure of the following:
- whether this still falls under "hacky code" mentioned in Hyprland's [PR Guidelines](https://wiki.hyprland.org/Contributing-and-Debugging/PR-Guidelines/#pr-requirements)
- variables like `drmName` and `drmVer` are `auto` instead of `auto const` - have followed the same convention for the newly introduced `drmVerName` variable
- whether there exist use cases with `evdi` drivers and using the passed-in `primary_` argument (I assume no)

displaylink fix: ignore primary argument when using evdi drivers

---

src/allocator/GBM.cpp

Make sure that format is supported by cursor plane even if it is not renderable.
Otherwise rendering will almost freeze if hardware cursors are enabled with nvidia.

Fix gbm cursor for nvidia

---

src/backend/Headless.cpp
src/backend/Wayland.cpp

fixes hyprwm/Hyprland#6995
Hyprland still holds ref to output so it isn't destroyed by std::erase, and destroy event isnt sent

fix destroying headless outputs

---

src/backend/Session.cpp

This fixes a bug, where the aquamarine switch state is never updated, thus the check `if (ENABLED == hlDevice->switchy->state)` blocks all "disabled" events (the default state) and only switch "enabled" events are fired.

Update switch state in libinput event

---

src/backend/drm/Renderer.cpp

Unbreak build on FreeBSD due to missing header

---

CMakeLists.txt

From cmake documentation, Linux-specific chapter:
>  Projects may use the ``OpenGL::GL`` target (or ``OPENGL_LIBRARIES``
>  variable) to use legacy GL interfaces.  These will use the legacy GL
>  library located by ``OPENGL_gl_LIBRARY``, if available.  If
>  ``OPENGL_gl_LIBRARY`` is empty or not found and GLVND is available,
>  the ``OpenGL::GL`` target will use GLVND ``OpenGL::OpenGL`` and
>  ``OpenGL::GLX`` (and the ``OPENGL_LIBRARIES`` variable will use the
>  corresponding libraries).  Thus, for non-EGL-based Linux targets, the
>  ``OpenGL::GL`` target is most portable.
which means linking with OpenGL::GL makes cmake find legacy libGL.so or GLX libraries, and as for now, the former contains GLX symbols and cannot be built without X libraries. Since we are working with EGL, it wouldn't …

cmake: link libOpenGL instead of legacy libGL

---

src/allocator/GBM.cpp

calculate the size to the stride we get from gb_bo_map to better align it.

buffer align size to stride

---

include/aquamarine/backend/DRM.hpp
src/backend/drm/DRM.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/6459
Needs a test run

drm: don't schedule new frame events on disabled outputs

---

src/backend/drm/DRM.cpp

dual gpus can init with no crtc and later rescan for them, however getRenderFormats might be called before that happends and null ptr deref, guard against it.

output avoid crashing on no crtc

---

src/backend/drm/DRM.cpp

related commit hyprwm/aquamarine@18c6a8c
fix for `[ERR] [AQ] atomic drm request: failed to commit: Device or resource busy, flags: ATOMIC_NONBLOCK PAGE_FLIP_ASYNC` hyprwm/Hyprland#7215

tearing fix

---

src/backend/Backend.cpp
src/backend/Headless.cpp

make the definition long long as its used as long long later, only the value was being calculated TIMESPEC_NSEC_PER_SEC * 240 and rolls over before assigning to the variable.
```
long long  lowestNs = TIMESPEC_NSEC_PER_SEC * 240 /* 240s, 4 mins */;
```

backends dont overflow on 32bit builds

---

src/backend/drm/DRM.cpp

scan connectors to get them
assign crtcs if they don't have them
then connect

don't connect before crtcs are guaranteed

---

docs/env.md
src/backend/drm/DRM.cpp

will hopefully mitigate or fix #76
plz test @romanstingler @techyporcupine

add AQ_NO_MODIFIERS to try to mitigate hardware limitations

---

src/allocator/GBM.cpp

The list of explicit modifiers wasn't updated when there are no RENDERABLEs, but then it is used even in that case.
This fixes https://github.com/hyprwm/aquamarine/issues/82

modifier list wasn't updated when renderable list was empty

---

src/backend/Backend.cpp
src/backend/Session.cpp

Dispatches libinput events when onReady is called. Prevents unread events on start
fixes https://github.com/hyprwm/Hyprland/issues/7855 https://github.com/hyprwm/Hyprland/issues/7391

Session: only dispatch udev in dispatchPendingEventsAsync if on linux

---

src/backend/Headless.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/7276
Fixes https://github.com/hyprwm/hyprlock/issues/434
I tested explicit modes for headless outputs and they are still created properly.
Should this mode set as preferred? It currently is.

output: add a default mode for headless outputs

---

CMakeLists.txt
flake.lock
include/aquamarine/backend/DRM.hpp
include/aquamarine/output/Output.hpp
src/backend/drm/DRM.cpp
src/backend/drm/Props.cpp
src/backend/drm/impl/Atomic.cpp
src/output/Output.cpp

ref https://github.com/hyprwm/hyprland-protocols/pull/10
ref https://github.com/hyprwm/aquamarine/issues/89

DRM: Implement CTM

---

src/backend/drm/DRM.cpp

fixes a crash because backend was null in DRMLease dtor lol
for hyprwm/Hyprland#8116

fix drm lease crash

---

src/backend/drm/DRM.cpp

Fixes this crash I got twice randomly when switching vts. Don't know how to reproduce the underlying buffer getting destroyed, but this probably fixes it.
```
#0  0x00007f7cef1b57dc in __pthread_kill_implementation ()
from /nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/libc.so.6
#1  0x00007f7cef163516 in raise ()
from /nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/libc.so.6
#2  0x00007f7cef14b935 in abort ()
from /nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/libc.so.6
#3  0x0000000000511b54 in handleUnrecoverableSignal(int) ()
#4  <signal handler called>
#5  0x00007f7cf02e6e26 in Aquamarine::CDRMBackend::restoreAfterVT (this=0x39d530e0)
at /build/5zx5awmf2jcg95wcmcnmpycz47xsl1ix-source/src/backend/drm/DRM.cpp:334
#6  0x00007f7cf02e74d8 in …
```

drm: guard cursorFB buffer in restoreAfterVT

---

src/backend/drm/DRM.cpp

seems pointless scanning the card[0-9]-eDP etc outputs for kms/bootvga/rendernodes just use the [0-9] cards, also safegaurd in commitstate for missing renderer prevents a coredump if __EGL_VENDOR_LIBRARY_FILENAMES is set to mesa on a laptop with dual gpus and a monitor attached to the nvidia dgpu. it might be a way to make this handled better but now it doesnt segfault atleast with a null dereference to renderer.

scan only cards and not outputs, safeguard against null renderer

---

src/backend/drm/impl/Atomic.cpp

During startup, CDRMAtomicImpl::reset() may emit a call to method commit of a CDRMAtomicRequest instance with member "conn" uninitialized, leading to a segfault. Validate the the pointer before dereference it as a workaround.
Fixes: 55ac962 ("DRM: preliminary atomic support")
Closes: https://github.com/hyprwm/aquamarine/issues/107

drm: Validate conn before dereference in CDRMAtomicRequest::commit()

---

include/aquamarine/backend/DRM.hpp
src/backend/drm/DRM.cpp

probably fixes hyprwm/Hyprland#8508 but author is unresponsive
either way this pr addresses
* drm connectors can be hotplugged by usb-c hubs
* recheckCRTCs -> scanConnectors -> new connector can be discovered and connected without crtc on second pass

clearer flow when rescanning connectors

---

src/allocator/GBM.cpp
src/backend/drm/DRM.cpp
src/backend/drm/Renderer.cpp

fixes hyprwm/Hyprland#8354
this does
* errors before alloc when plane or backend doesn't support requested format in gbm
* allow implicit modifier buffers to be allocated by not forcing linear in gbm
* allow implicit modifiers to be added to glFormats
* allow the blit to_buffer to use external formats (cause implicit is external)

allow multigpu blit from explicit to implicit

---

src/backend/drm/DRM.cpp

might or might not fix #110, author hasn't responded
but i think this pr makes sense anyways
drm_minor => ex. card1 and render128
drm_connector => ex. card1-DP-1 or card1-HDMI-A-1

udev scan only cards (drm_minor), not connectors (drm_connector)

---

src/backend/drm/impl/Atomic.cpp

drmModeAtomicCommit sets errno sometimes instead of returning it...
ex. returns -1 but errno = ENOMEM

log errno set by drmModeAtomicCommit

---

src/backend/drm/DRM.cpp

closes #109
early return added in #106 broke `virtio-vga-gl`, moves the check to blitting
tested locally with nixos both via qemu and host configuration with no issues

drm: moved null check for renderer to shouldBlit() (#109)

---

src/backend/drm/DRM.cpp

fixes hyprwm/Hyprland#8790
edit:
it think fixes #117 also

only fail INVALID format when it's set as that

---

src/backend/drm/DRM.cpp

drm: work around missing drm_minor on FreeBSD

---

include/aquamarine/allocator/Allocator.hpp
include/aquamarine/allocator/GBM.hpp
include/aquamarine/backend/Backend.hpp
include/aquamarine/backend/DRM.hpp
src/allocator/Allocator.cpp
src/allocator/GBM.cpp
src/backend/Backend.cpp
src/backend/Session.cpp
src/backend/drm/DRM.cpp
src/backend/drm/Renderer.cpp
src/backend/drm/Renderer.hpp

I have a Lenovo Legion 5 Pro (16ACH6H) laptop with an AMD iGPU and an NVIDIA dGPU. I want the flexibility to use different modules for the dGPU depending on my needs:
1. **No module**: startup and power-saving.
2. **`vfio-pci`**: For passthrough to a vm.
3. **`nouveau`**: To use the connectors connected to the dGPU exclusively for driving additional monitors.
4. **`nvidia` (without modesetting)**: For CUDA workloads, offloaded rendering, etc.
---
1. **Load nouveau**:  
I can now use the outputs connected to my dGPU only.
2. **Signal Aquamarine to release the dGPU**:
```bash
udevadm trigger --type=devices --action=remove --subsystem-match=drm --property-match="MINOR=0"
```
3. **Unload nouveau and load something else.**
---
I'm happy to take this to the finish line in case any changes are …

GPU hotplug support

---

src/backend/drm/impl/Atomic.cpp

Missed some properties while moving to separate function. Those might incorrectly reset the state.

remove wrong property settings

---

.clang-tidy
src/allocator/GBM.cpp
src/allocator/Swapchain.cpp
src/backend/Backend.cpp
src/backend/Headless.cpp
src/backend/Session.cpp
src/backend/Wayland.cpp
src/backend/drm/DRM.cpp
src/backend/drm/Props.cpp
src/backend/drm/Renderer.cpp
src/backend/drm/impl/Atomic.cpp
src/backend/drm/impl/Legacy.cpp

`.clang-tidy` stolen from Hyprland, yeah
Is there any ABI break?

Core: add clang-tidy

---

src/backend/Headless.cpp

fix hyprwm/Hyprland#8806
grabs EGL formats from DRM backend or uses a set of usually supported formats

fix headless supported formats

---

include/aquamarine/output/Output.hpp
src/backend/drm/impl/Atomic.cpp
src/output/Output.cpp

API to set drm content type property. https://drmdb.emersion.fr/properties/3233857728/content%20type
Nvidia doesn't support it. Untested. Probably needs monitor support to be useful.

Support setting drm content type property

---

CMakeLists.txt
src/allocator/DRMDumb.cpp
src/backend/Session.cpp
src/backend/Wayland.cpp
src/backend/drm/DRM.cpp
src/backend/drm/Props.cpp
src/backend/drm/Renderer.cpp

As i said in the title
There's only 5 warnings left
3 of them is unused variable, 1 unused, but set variable and a implicit fallthrough

Compiler fixes and options

---

src/backend/drm/Renderer.cpp

realized while looking back at #114, oops

drm: only allow multigpu blit to implcit, not all external formats

---

src/backend/drm/DRM.cpp

kinda ref hyprwm/Hyprland#9284
also https://gitlab.freedesktop.org/drm/amd/-/issues/3673
basically bootVGA is sometimes wrong, so detect amount of internal panels to find iGPU

prioritize gpus with the most internal panels

---

src/backend/drm/DRM.cpp
src/backend/drm/impl/Atomic.cpp

kinda reverts 4468981c, really just fixes it better
probably fixes #125
also fixes issue I observed where hw pointer isn't reset on vt switch so you can get a cursor on multiple screens
edit:
btw the `&conn->pendingPageFlip` paramter is just a classic `void* data` and its ok to set null

fix atomic reset being skipped, check nullptr elsewhere instead

---

src/backend/drm/Renderer.cpp
src/backend/drm/Renderer.hpp

Using RAII to manage the EGL context:
- Correctly restores the EGL context if an early return occurs due to an error
- Correctly handles recursive Renderer calls (though we don't do any at the moment, #147 only calls a separate Renderer)
- Prevents other code oversights like forgetting to call restoreEGL()
I took inspiration from the std::lock_guard API for this, but I haven't worked in C++ for a while so let me know if there's a better API.
This has a small conflict with #147 but I can resolve that depending on which one gets merged first.

drm: Use RAII to manage EGL context

---

src/allocator/GBM.cpp
src/backend/drm/DRM.cpp
src/backend/drm/Renderer.cpp
src/backend/drm/Renderer.hpp

This PR has two commits to fix running aquamarine against multiple Nvidia GPUs which provide different output monitors:
- A small commit to not force linear allocation on devices which don't support it, even if multigpu is enabled. This is necessary as Nvidia doesn't support the linear format.
- A Renderer commit to, if creating an EGL image from the source buffer fails, instead copy it to an intermediate buffer on the CPU memory first, then copy that intermediate buffer to the output buffer. This fixes Nvidia multigpu because Nvidia doesn't support attaching another gpu's buffer as an EGL image, so instead this PR first reads the source buffer into CPU memory using the primary renderer's EGL context, and then does the rest of the blit as normal on the secondary GPU which writes to the …

Fix multi-GPU support for Nvidia

---

include/aquamarine/backend/DRM.hpp
include/aquamarine/misc/Attachment.hpp
src/backend/drm/DRM.cpp
src/backend/drm/Renderer.cpp
src/backend/drm/Renderer.hpp
src/misc/Attachment.cpp

Feel free to reject this PR if the new abstraction is too complicated or otherwise not your preference, but it fixes a couple of potential pitfalls and simplifies the external API:
- You no longer have to manage the eAttachmentType and figure out which enum values correspond to which types. This also makes it easier to add new attachment types in the future, and provides flexibility to use this in other non-DRM contexts or with external attachment types.
- You no longer have to cast returned attachments to the right type, as the attachment manager now does the cast for you. This also avoids the potential pitfall of casting to the wrong attachment type.
- Previously, we called `removeByType` before `add` because it was possible to have multiple attachments of the same type by accident, but …

misc: Add strict typing to attachment manager

---

src/backend/drm/DRM.cpp

only scan connected connectors when deciding which gpu to become primary mux switched laptops still have connectors for internal panel but not connected.
fixes #153 
thanks @ikalco , who technically wrote the patch.

drm: only scan connected connectors

---

src/backend/Wayland.cpp

The old code was crashing for me on shutdown due to the fact that `CWaylandBackend`'s reverse field order destruction destroys `idleCallbacks` before destroying `outputs`, meaning that when `~CWaylandOutput` calls `backend->idleCallbacks.clear();` it's clearing an already destroyed vector which crashes.
To fix this I just removed the FIXME hack and properly handled the potential `sendFrameAndSetCallback` UAF by using the weak pointer to check if the output was already destroyed or not.

backend: Fix Wayland backend idleCallbacks destruction

---

CMakeLists.txt
flake.lock
include/aquamarine/misc/Attachment.hpp
src/misc/Attachment.cpp
tests/Attachments.cpp
tests/shared.hpp

Requires https://github.com/hyprwm/hyprutils/pull/47
Some compilers (apparently gcc though I wasn't able to replicate) are complaining about the old code violating the strict-aliasing rule. This new code avoids using raw pointer casts and instead just creates a new shared pointer out of the old one with the new force reinterpret functionality from the above mentioned PR.

misc: Fix Attachment shared pointer reinterpret

---

include/aquamarine/backend/Backend.hpp
include/aquamarine/backend/DRM.hpp
include/aquamarine/backend/Headless.hpp
include/aquamarine/backend/Wayland.hpp
src/allocator/GBM.cpp
src/backend/Headless.cpp
src/backend/Wayland.cpp
src/backend/drm/DRM.cpp

Swapchains were created with the primary allocator, but the output's backend. This meant that the wrong format would be selected with multi-GPU setups such as NVIDIA primary and Intel secondary. We still try to use the LINEAR format if available, but if it's not available, we should use the format from the primary GPU instead of the secondary GPU.
My previous PR https://github.com/hyprwm/aquamarine/pull/147 fixed having two NVIDIA GPUs or having Intel as primary and NVIDIA as secondary, but this PR fixes having NVIDIA as primary and an Intel as secondary. Previously, the swapchain would create an Intel format buffer to render to for the secondary monitor, which NVIDIA would then fail to read due to being an unsupported format. Now, it'll correctly create an NVIDIA format buffer for the …

backend, allocator: Fix multi-GPU format selection

---

src/backend/Backend.cpp
src/backend/Headless.cpp
src/backend/Session.cpp
src/backend/Wayland.cpp

This PR should have no effect to behavior but cleans up compiler warnings (mostly removing unused variables)

backend: Fix compiler warnings

---

src/backend/drm/DRM.cpp

Should fix https://github.com/hyprwm/Hyprland/issues/9724
Couldn't replicate the issue. HDR settings are checked before every commit. The only way this can happen is when `output->state->state().hdrMetadata` doesn't match the real drm state.

Restore hdr metadata after vt switch

---

src/backend/drm/impl/Atomic.cpp

the compiler tries to optimize this and inlines the +=, which might involve raw memcpy operations, and in doing so, it thinks there is a chance that the internal buffer doesnt have enough space. use ostringstream instead, and return the string from that.
```
In function ‘copy’,                                                                                                                         
inlined from ‘_S_copy’ at /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/basic_string.h:435:21,                               
inlined from ‘_M_append’ at /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/basic_string.tcc:421:19,                           
inlined from ‘append’ at /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/basic_string.h:1485:18, …
```

atomic: fix compiler warning with string

---

src/backend/drm/Renderer.cpp

dont call glflush when its not needed, avoid vector reallocations in waitOnSync and guard glgeterror behind AQ_TRACE

a few small renderer optimisations

---

src/backend/drm/Renderer.cpp
src/backend/drm/Renderer.hpp

use const refs where applicable, make sgltex a uniqueptr and weakptr reference it.

reduce a bit of local temporar copies going around in renderer

---

CMakeLists.txt
flake.lock
include/aquamarine/backend/DRM.hpp
src/backend/drm/DRM.cpp
src/backend/drm/Props.cpp
src/backend/drm/impl/Atomic.cpp
src/backend/drm/impl/Legacy.cpp

dont use anonymous structs, iso c++ forbids it. compound literals is a c99 thing use designated c++20 initializing instead.
lets us catch issues ahead of time rather then later.

core: use -Wpedantic and fix warnings

---

include/aquamarine/backend/Session.hpp
src/backend/Session.cpp

The old way of handling tablet axis changes causes some changes to be missed.
For example, the pressure reaches 0 on tip up. So before this, when the pen gets out of contact, the pressure was always non-zero.
And while non-zero pressure is allowed by the tablet protocol, some apps can not work correctly. (I have seen it with some apps on Wine)

libinput: handle tablet axis on proximity, tip and button events

---

include/aquamarine/backend/Backend.hpp
include/aquamarine/backend/DRM.hpp
include/aquamarine/backend/Headless.hpp
include/aquamarine/backend/Session.hpp
include/aquamarine/backend/Wayland.hpp
src/backend/Backend.cpp
src/backend/Headless.cpp
src/backend/Session.cpp
src/backend/Wayland.cpp
src/backend/drm/DRM.cpp

make a getter for drmRenderNodeFD() so we can create sync timelines on the rendernode on devices not supporting fences on the card* device directly.
add the rendernode matching the drm card if there is one. if none exist fallback to first found.

core: introduce drmRenderNodeFD()

---

src/allocator/GBM.cpp
src/include/Shared.hpp
src/utils/Shared.cpp

Makes the behavior introduced in #174 default. I've confirmed that the fallback in case linear allocation fails means that this still works on NVIDIA<>NVIDIA. I left the env around in case it needs disabled, but since the new behavior seems to work on both NVIDIA<>NVIDIA and AMD<>AMD I think we should be good.
Fixes #196 by forcing linear allocation to avoid CPU blitting on AMD<>AMD.

allocator: Default to forcing linear blit for multigpu

---

src/backend/drm/DRM.cpp

if the backends now gets a rendernode it wont call the authmagic on the displaynode making dumb buffer creation failing on certain drivers. so reopen it again in the creation of the CDRMDumbAllocator.
im not sure if this breaks it further, or actually solves it. i cant even reproduce it. the only place so far i noticed this happening is on the nix test suite on hyprland. https://github.com/hyprwm/Hyprland/actions/runs/17022533814/job/48253900013?pr=11087#step:5:5414
ive tested intel only, nvidia only, and intel + nvidia. so idk

drmdumb: reopen displaynode

---

src/backend/Backend.cpp
src/backend/drm/DRM.cpp

either there is a fd going wrong here or certain drivers just plain fails with this. revert for now. but leave the cdrmrenderer using rendernode. 
cant reproduce it locally but CI running llvmpipe and virtualmachine fails on hyprland.

render: revert #203 and half of #202

---

src/backend/drm/DRM.cpp

evdi/displaylink devices doesnt give us a rendernode at all, and asahi was hard to associate if a rendernode was related to the displaynode/card so we fallback to just first found if that occurs. might be more appropiate to figure out a proper way to deal with these cases then workaround ever single driver that doesnt give rendernodes but so far seems only to be evdi.
problem that occured is a 3 gpu situation, the evdi card ended up using a rendernode for a complete different gpu because it fallbacked to that.
fixes: #210

rendernode: dont bother finding one on evdi
